
*   ## **01 Data Types and Data Structures**





*  #  Tipos de variables


In [ ]:
#1ero
string1 = 'Bienvenido a'
string2 = "QuantConnect"
print(string1 + ' ' + string2)

Bienvenido a QuantConnect


In [ ]:
#2do
int1 = 20
print(int1)
print(type(int1))

20
<class 'int'>


In [ ]:
#3ero
string1 = "5"
print(type(string1))
int1 = int(string1)
print(type(int1))

<class 'str'>
<class 'int'>


In [ ]:
#4to
string1 = "5"
float1 = float(string1)
print(type(float1))

<class 'float'>


In [ ]:
#5to
bool1 = False
print(bool1)
print(type(bool1))

False
<class 'bool'>


In [ ]:
#6to
print("Suma", 2+3)
print("Resta", 57-23)
print("Multiplicación", 0.8*100)
print("División", (75/10))
print("Potencia", 5**5)

Suma 5
Resta 34
Multiplicación 80.0
División 7.5
Potencia 3125


In [ ]:
#Operaciones matematicas basicas
print(2/5)
print(2.0/5)

0.4
0.4



*  #  Data Collections


In [ ]:
#Lista - 1ero
mi_lista = ['Neiva', 'Pitalito', 6,6,2]
print(mi_lista)

['Neiva', 'Pitalito', 6, 6, 2]


In [ ]:
#2do
mi_lista = ['Neiva', 'Pitalito', 6,6,2]
print(len(mi_lista))
print(mi_lista[0])
print(mi_lista[len(mi_lista) -1])

5
Neiva
2


In [ ]:
#3ero
mi_lista = ['Neiva', 'Pitalito', 6,6,2]
mi_lista[2] = 'Bogotá'
print((mi_lista))

['Neiva', 'Pitalito', 'Bogotá', 6, 2]


In [ ]:
#4to
mi_lista = ['Neiva', 'Pitalito', 6,6,2]
print(mi_lista[0:2])
print(mi_lista[2:])
print(mi_lista[:3])

['Neiva', 'Pitalito']
[6, 6, 2]
['Neiva', 'Pitalito', 6]


In [ ]:
#5to
mi_lista2 = ['Salut','tu','fais']
mi_lista2.append('quoi')
mi_lista2.append('?')
print(mi_lista2)

mi_lista2.remove("Salut")
print(mi_lista2)

['Salut', 'tu', 'fais', 'quoi', '?']
['tu', 'fais', 'quoi', '?']



*   # Tupla


In [ ]:
#Similares a las listas pero inmutable
mi_tupla = ('Bienvenido','a','la', 'UNAL')
print(mi_tupla[1:])

('a', 'la', 'UNAL')


*   # Set

In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
aeropuertos = set(aeropuertos)
print(aeropuertos)

{'BOG', 'CDG', 'NVA', 'MEX', 'LAX'}


*   # Diccionario


In [ ]:
FRANCES_ESPAÑOL = {'Salut':'Hola', 'Quoi': 'Que', 'Vrai': 'Verdad'}
print(FRANCES_ESPAÑOL['Salut'])

FRANCES_ESPAÑOL['Vrai'] = 'Cierto'
print(FRANCES_ESPAÑOL['Vrai'])
print(FRANCES_ESPAÑOL.keys())

Hola
Cierto
dict_keys(['Salut', 'Quoi', 'Vrai'])


*   # Operaciones comunes con Strings


In [ ]:
my_str = 'I dont want to say goodbye, i think we can do it if we try'
print(my_str[28:])

i think we can do it if we try


In [ ]:
print("J'tombe amoureuse assez souvent".count('e'))
print("J'tombe amoureuse mais t'exagères".find('e'))
print("Ça s'entretient les sentiments".replace('Ç','c'))

5
6
ca s'entretient les sentiments


In [ ]:
#Tiempo
Nacimiento = '2021-07-15 08:33:00'
Lista_Dividida = Nacimiento.split(' ')
Fecha = Lista_Dividida[0]
Tiempo = Lista_Dividida[1]
print(Fecha, Tiempo)
Hora = Tiempo.split(':')[0]
print(Hora)

2021-07-15 08:33:00
08


In [ ]:
Hora_Nacimiento = 'Hora: {}, Minutos:{}'.format('08','33')
print(Hora_Nacimiento)

Hora: 08, Minutos:33


In [ ]:
print('Mi edad es %f'%18.0)
print('%s %s es %s'%('Mi','nombre', 'Gabriel'))

Mi edad es 18.000000
Mi nombre es Gabriel


## **02 Logical Operations and Loops**

In [ ]:
print(25 == 20)
print(30 == 30)
print(3 != 2)
print(10 >= 10)
print(3 >= 9)

In [ ]:
print(22 > 5 and 10 > 1)
print(4 > 2 and 17 < 3) 
print(5 > 0 or 20 < 10)
print(80 < 8 and 2 < 2)

True
False
True
False


In [ ]:
print(21 > 3 or 20 < 21 and (5!=3 and 7>2) and not ( 6 < 1 or 2 < 12 and (3!=1 and 57>56)))

print((5 > 1 or 4 < 9) and (2!=2 and 7>6) and not ( 0 < 1 or 2 < 5 and (1!=5 and 2>1)))

True
False




 * #  If Statement

In [ ]:
l = 25
if l != 0:
    print('l!=0 es True')

l!=0 es True


In [ ]:
p = 10 > 30
q =  15 < 150  
if p and q:
    print('p y q son True')
elif p and not q:
    print('q es False')
elif q and not p:
    print('p es False')
else:
    print('Ni p y q son True')

p es False


 * #  While Loop

In [ ]:
l = 15
while l < 55:
  print(l)
  l += 5

15
20
25
30
35
40
45
50


 * #  For Loop

In [ ]:
vocales = ['a','e','i','o','u']
for l in vocales:
  print(l)

a
e
i
o
u


In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
viaje = ['NVA','BOG']
visitados = []
for l in aeropuertos:
  if l not in viaje:
    visitados.append(l)
print(visitados)

['CDG', 'LAX', 'MEX', 'LAX', 'MEX']


 * #  Break and continue

In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
for l in aeropuertos:
  print(l)
  if l == 'NVA':
    break

CDG
LAX
MEX
NVA


In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
for l in aeropuertos:
  if l == 'LAX' or l == 'MEX':
    continue
  print(l)

CDG
NVA
BOG


 * #  List Comprehension

In [ ]:
squares_root = []
for i in [25,49,64,81,121]:
    squares_root.append(i**(1/2))
print(squares_root)

[5.0, 7.0, 8.0, 9.0, 11.0]


In [ ]:
numeros = [25,49,64,81,121]
squares_root = [x**(1/2) for x in numeros]
print(squares_root)

[5.0, 7.0, 8.0, 9.0, 11.0]


In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
visitados = ['CDG','BOG','NVA','CUN']
visitas = [x for x in visitados if x in aeropuertos]
print(visitas)

['CDG', 'BOG', 'NVA']


In [ ]:

print([(x, y) for x in [6,1,6] for y in [9,3,6] if x != y])
print([str(x)+' vs '+str(y) for x in ['CDG', 'LAX', 'MEX'] for y in ['NVA', 'LAX', 'MEX', 'BOG'] if x!=y])

[(6, 9), (6, 3), (1, 9), (1, 3), (1, 6), (6, 9), (6, 3)]
['CDG vs NVA', 'CDG vs LAX', 'CDG vs MEX', 'CDG vs BOG', 'LAX vs NVA', 'LAX vs MEX', 'LAX vs BOG', 'MEX vs NVA', 'MEX vs LAX', 'MEX vs BOG']


*  ## **03 Functions and Objective-Oriented Programming**


 *   # **Built-in Function**

In [ ]:
def product(x,y):
    return x/y
print(product(20, 5))
print(product(50,10))

4.0
5.0


In [ ]:
def te_amo():
    print("Je t'aime")
te_amo()

Je t'aime


In [ ]:
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
print('Los aeropuertos visitados son {}'.format(len(aeropuertos)))
for l in range(len(aeropuertos)):  
  print(aeropuertos[l])

Los aeropuertos visitados son 7
CDG
LAX
MEX
NVA
LAX
MEX
BOG


In [ ]:
#map -function that applies a function to every item and returns a list of the results.
aeropuertos = ['CDG', 'LAX', 'MEX', 'NVA', 'LAX', 'MEX', 'BOG']
print(list(map(len,aeropuertos)))

rango= list(map(lambda x: x**3, range(10)))
print(rango)

dos_arrays = list(map(lambda x, y: x*y, [5,4,3,2,1],[9,8,7,6,5]))
print(dos_arrays)

dos_arrays= sorted(dos_arrays)
print(dos_arrays)


[3, 3, 3, 3, 3, 3, 3]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
[45, 32, 21, 12, 5]
[5, 12, 21, 32, 45]


In [ ]:
#Se puede agregar el parametro "llave"
price_list = [('NVA-BOG',200),('BOG-MED',80),('BOG-CUN',600),('BOG-CTG',120)]
print(sorted(price_list, key = lambda x: x[1]))
print(sorted(price_list, key = lambda x: x[1],reverse = True))

price_list.sort(key = lambda x: x[1])
print(price_list)

[('BOG-MED', 80), ('BOG-CTG', 120), ('NVA-BOG', 200), ('BOG-CUN', 600)]
[('BOG-CUN', 600), ('NVA-BOG', 200), ('BOG-CTG', 120), ('BOG-MED', 80)]
[('BOG-MED', 80), ('BOG-CTG', 120), ('NVA-BOG', 200), ('BOG-CUN', 600)]



 *   # **POO**




In [7]:
#Clase - Es un tipo de dato. Cuando creamos un objeto, lo llamamos instancia de la clase.
#Los datos guardados dentro de un objeto son llamados atributos.
#Las funciones asociadas a ese objeto se llaman metodos.
import math
class Punto:
    #init method or constructor
    def __init__(self, x= None, y = None):
        self.x = x
        self.y = y

 
    def distancia_xy(self):
        #dx = self.x[1] - self.x[0]
        #dy = self.y[1] - self.y[0]
        #return(math.sqrt(dx**2 + dx**2))
        return((((self.x[1]-self.x[0])**2) + ((self.y[1]-self.y[0])**2)) ** (1/2))
p1 = Punto([-1,3],[7,4])
d1 = p1.distancia_xy()
print(d1)
#p1.ceo = (9,8)
#p1.ceo
#dir(p1)



5.0


 *   # **Herencia**

In [8]:
class area(Punto):
     def __init__(self,z = None):
        self.z = z 
p2 = area([5,9])


## **04 NumPy and Basic Pandas**

In [9]:
import numpy as np
precios = [50,70,260,935]
lista_precios = np.array(precios)
print(lista_precios, type(lista_precios))

[ 50  70 260 935] <class 'numpy.ndarray'>


In [16]:
Dimensiones = np.array([[5,7],[3,9]])
print(Dimensiones, type(Dimensiones))

print(Dimensiones.shape)

print(Dimensiones[0])
print(Dimensiones[1])

print('La primera columna: ', Dimensiones[:,0])
print('La segunda columna: ', Dimensiones[:,1])

[[5 7]
 [3 9]] <class 'numpy.ndarray'>
(2, 2)
[5 7]
[3 9]
La primera columna:  [5 3]
La segunda columna:  [7 9]


 *   # **Array Functions**


In [18]:
print(np.log(precios))
print(np.mean(precios))
print(np.std(precios))
print(np.sum(precios))
print(np.max(precios))

[3.91202301 4.24849524 5.56068163 6.84054653]
328.75
359.4853091574119
1315
935


 *   # **Pandas**


In [22]:
import pandas as pd
masa = [55,58,60,75,64,45]
s = pd.Series(masa)
s

0    55
1    58
2    60
3    75
4    64
5    45
dtype: int64

In [23]:
s = pd.Series(masa,index = ['a','b','c','d','e','f'])
s

a    55
b    58
c    60
d    75
e    64
f    45
dtype: int64

In [24]:
s.index = [6,5,4,3,2,1]
s

6    55
5    58
4    60
3    75
2    64
1    45
dtype: int64

In [26]:
print(s[2:])
print(s[:-3])

4    60
3    75
2    64
1    45
dtype: int64
6    55
5    58
4    60
dtype: int64


In [27]:
print(s[2])
s[2] = 87
print(s)

64
6    55
5    58
4    60
3    75
2    87
1    45
dtype: int64


In [29]:
s = pd.Series(masa, name = 'Masa de vecinos del piso 7')
print(s)
print(s.name)
print(s.describe())

0    55
1    58
2    60
3    75
4    64
5    45
Name: Masa de vecinos del piso 7, dtype: int64
Masa de vecinos del piso 7
count     6.000000
mean     59.500000
std       9.934787
min      45.000000
25%      55.750000
50%      59.000000
75%      63.000000
max      75.000000
Name: Masa de vecinos del piso 7, dtype: float64


 *   # **Time Index**


In [32]:
time_index = pd.date_range('2021-10-15',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2021-10-15', '2021-10-16', '2021-10-17', '2021-10-18',
               '2021-10-19', '2021-10-20'],
              dtype='datetime64[ns]', freq='D')
2021-10-15    55
2021-10-16    58
2021-10-17    60
2021-10-18    75
2021-10-19    64
2021-10-20    45
Freq: D, Name: Masa de vecinos del piso 7, dtype: int64


In [33]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[3])

6    55
5    58
4    60
3    75
2    64
1    45
Name: Masa de vecinos del piso 7, dtype: int64
75


In [34]:
print(s.iloc[3])

75


In [35]:
s.index = time_index
print(s['2021-10-20'])

45


In [36]:
print(s['2021-10-16':'2021-10-19'])

2021-10-16    58
2021-10-17    60
2021-10-18    75
2021-10-19    64
Freq: D, Name: Masa de vecinos del piso 7, dtype: int64


In [37]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2021-10-15    55
2021-10-16    58
2021-10-20    45
Name: Masa de vecinos del piso 7, dtype: int64
[2021-10-15    False
2021-10-16    False
2021-10-17     True
2021-10-18    False
2021-10-19     True
2021-10-20    False
Freq: D, Name: Masa de vecinos del piso 7, dtype: bool]
